name: Build
 
on:
 push:
   branches:
     - main
 
 pull_request:
   branches:
     - main
 
jobs:
 docker:
   name: Build Docker container
   runs-on: ubuntu-latest
   steps:
       - name: Checkout
         uses: actions/checkout@v2
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
       - name: Build and push
         uses: docker/build-push-action@v2
         with:
           context: .
           push: false
           tags: myportfolio:latest
